### ISSUE TITLE
上傳大檔(4.3GB)時會出現 ERR_CONNECTION_ABORTED

### ISSUE THREAD

**Issue by yeungalan** [tobychui/ArOZ-Omega-Online#1]
當上傳太大的檔案時會出現錯誤。
![default](https://cloud.githubusercontent.com/assets/12872405/25129427/9b3fa520-2470-11e7-99f8-67e62b948c76.png)

**Comment by tobychui** [comment]
It seems not the problem of the ArOZ Online System.
Please attach your web server setting file / important information on the max_uplaod_size and timeout value from your PHP.ini or setting files equivalent to the PHP.ini.
