### ISSUE TITLE
I can't upload my file :(

### ISSUE THREAD

**Issue by Asteriska001** [tobychui/ArOZ-Omega-Online#3]
Hmmm... I can;t upload any file via the upload page.
 Just like this..
![image](https://user-images.githubusercontent.com/15817126/49447568-d6ff7b00-f811-11e8-88cd-f56868e9b01a.png)
I tried to set up the project in Windows and Linux,but both of them were failed....
More details.:
![image](https://user-images.githubusercontent.com/15817126/49447801-5ab96780-f812-11e8-8aed-3bc764415340.png)

**Comment by tobychui** [comment]
Hi, thanks for your comment. You might notice that this project is no longer supported (and yes, we are working on the BETA version of this software). One tips for you is that you might have an incorrect setting in php.ini.  Check the php.ini and find the line
```
upload_max_filesize=
post_max_size=
```
And set them to what you needed. the default value is 8M on debian Jessie and 2048M is recommended.
Please send me an email directly if you still need any assistance as I seldom check the Github for issue. Thanks :)

**Comment by Asteriska001** [comment]
Thanks
